### PR TITLE
fix: Links in the footer to the guides

### LINKED ISSUE #14: Update footer links to guides
Upon finishing #13 we need to update footer links to the main guides.
At the moment it points to the stand alone pages, it must point to the tabs content instead.
So when the user click the link they needs to be redirected to the guides page and the appropriate tab must be opened.

### PR DESCRIPTION
**Pull request by gridcat**
Links in the footer to switch the tabs instead of redirection

Fixes #14

### CODE REVIEW

**Comment by gridcat** [comment]
Latest changes will fix #34 as well

**Comment by RoboticMind** [comment]
These links in the footer appear to not scroll or change the guide when clicked on the guide pages. Probably need to add a hashchanged listener https://developer.mozilla.org/en-US/docs/Web/API/Window/hashchange_event

**Comment by gridcat** [comment]
@RoboticMind please revisit

**Review by RoboticMind — APPROVED** [review]
Looks good to me now

**Pull request merged**
